// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6WwubjgPB9g6Nb08ZJrr9iUcBVzsz6pI',
    appId: '1:611396213310:web:c13875776f67b7b6bfcf6f',
    messagingSenderId: '611396213310',
    projectId: 'hydrax-23',
    authDomain: 'hydrax-23.firebaseapp.com',
    storageBucket: 'hydrax-23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDouR6K6gPhZtjw7wFtT8auyLK4zeihBB0',
    appId: '1:611396213310:android:e7dcd5eedc852ff3bfcf6f',
    messagingSenderId: '611396213310',
    projectId: 'hydrax-23',
    storageBucket: 'hydrax-23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOi9euvCWJsWliN7gspZT_ESDbJ_pAsBA',
    appId: '1:611396213310:ios:cd4f00b499188d29bfcf6f',
    messagingSenderId: '611396213310',
    projectId: 'hydrax-23',
    storageBucket: 'hydrax-23.firebasestorage.app',
    iosBundleId: 'com.example.android',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOi9euvCWJsWliN7gspZT_ESDbJ_pAsBA',
    appId: '1:611396213310:ios:cd4f00b499188d29bfcf6f',
    messagingSenderId: '611396213310',
    projectId: 'hydrax-23',
    storageBucket: 'hydrax-23.firebasestorage.app',
    iosBundleId: 'com.example.android',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6WwubjgPB9g6Nb08ZJrr9iUcBVzsz6pI',
    appId: '1:611396213310:web:d2012f7e8616dc78bfcf6f',
    messagingSenderId: '611396213310',
    projectId: 'hydrax-23',
    authDomain: 'hydrax-23.firebaseapp.com',
    storageBucket: 'hydrax-23.firebasestorage.app',
  );
}
